_homepage:
    pattern:  /
    defaults: { _controller: WimpAppBundle:Video:index }

video_view:
    pattern: /view/{slug}
    defaults: 
        _controller: WimpAppBundle:Video:view
        slug: video-0

video_get_nextorprev:
    pattern: /videos/{id}
    defaults: 
        _controller: WimpAppBundle:Video:getVideos
        id: 1
    requirements:
        id: \d+

video_search:
    pattern: /videos/{searchWord}
    defaults: 
        _controller: WimpAppBundle:Video:searchVideos
        id: 1
    requirements:
        id: "[a-zA-Z0-9\-\%]"

video_randomize:
    pattern: /randomize
    defaults:
        _controller: WimpAppBundle:Video:randomizeVideos