_homepage:
    pattern:  /
    defaults: { _controller: WimpAppBundle:Default:index }

video_view:
    pattern: /view/{slug}
    defaults: 
        _controller: WimpAppBundle:Default:view
        slug: video-0
video_get_list:
    pattern: /videos/{index}
    defaults: 
        _controller: WimpAppBundle:Default:view