parameters:
#    wimp_app.example.class: Wimp\AppBundle\Example

services:
    my.subscriber:
        class: Wimp\AppBundle\Entity\VideoListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }